watch_interval_sec: 1
aod_output_dir: /var/log/aod

watcher:
  actions:
    - dmesg
    - journalctl
    - debugdata
    - stats         # I'm assuming this refers to cifs stats

guardian:
  anomalies:
    error:
      type: "Error"
      tool: "smbiosnoop"
      mode: "trackonly"        # Options: all, trackonly, excludeonly
      acceptable_count: 10  # % of error responses in X seconds
      track_codes:              # Error codes to track
        - EACCES
        - EAGAIN
        - EIO
      # exclude_codes:          # Error codes to exclude, not to be used with trackonly
      #   - ENOENT
      actions:
        - dmesg
        - journalctl           # can add another eBPF tool to trigger here too


    # Refer to the note below for more info
    latency:
      type: "Latency"
      tool: "smbslower"
      mode: "all"              # Options: all, trackonly, excludeonly
      acceptable_count: 10     # number of commands with latency above threshold in X seconds
      default_threshold_ms: 20 # milliseconds, by default applies to all commands
      track_commands:
        - command: SMB2_WRITE
          threshold: 50
      actions:
        - dmesg
        - journalctl           
        - debugdata
        - stats
        - mounts
        - smbinfo
        - syslogs

cleanup:
  cleanup_interval_sec: 60     # Interval in seconds to run cleanup
  max_log_age_days: 2          # Maximum age of logs in days
  max_total_log_size_mb: 0.5   # Maximum total size of all logs in MB

audit:
  enabled: true

# ** Use either track_commands (trackonly) or exclude_commands (excludeonly).
# Mode type will determine which one is used.
# With Mode type all, track commands with the given thresholds,
# track other commands with the default threshold, and ignore the excluded commands.