---
controller_config:
  # Version of the controller configuration
  version: 1

  # Number of CPUs that the controller can consume
  cpu_limit: 1

  # Amount of memory (in MB) that the controller can consume
  memory_limit: 2048

  # Total amount of storage space (in MB) to consume on disk while running
  storage_limit: 1024

  # Directory to store the report tarballs
  output_directory: "/var/log/linux_diagnostics"

  # Total number of report tarballs to keep. Older ones will be deleted.
  max_output_tarballs: 24

  # Dictionary of anomaly types to track and their respective arguments
  anomalies:
    cifs:
      server_latency:
        arguments:
          all: 100
      vfs_callback_latency:
        arguments:
          all: 200
      server_errors:
        arguments:
          all:
      vfs_callback_errors:
        arguments:
          all:
    nfs:
      server_latency:
        arguments:
          all: 100
      vfs_callback_latency:
        arguments:
          all: 200
      server_errors:
        arguments:
          all:
      vfs_callback_errors:
        arguments:
          all: